### ISSUE TITLE
sp.tum.sexy wrong location

### ISSUE THREAD

**Issue by konrad2002** [TUM-Dev/TUM.sexy#181]
sp.tum.sexy points to 
```https://www.in.tum.de/in/fuer-studierende/bachelor-studiengaenge/informatik/studienplan/studienbeginn-ab-wise-202122/```
but it should be
```https://www.in.tum.de/in/fuer-studierende/bachelor-studiengaenge/informatik/studienplan/studienbeginn-ab-wise-2021-22/```

**Comment by joschahenningsen** [comment]
fixed int #180 180
