### ISSUE TITLE
Links pointing to in.tum.de not working

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/TUM.sexy#237]
For some URLs like mai.tum.sexy (redirecting to Grundlagen KI)we redirect, despite this not being in the list of redirects.
It is not transparent to me, where this behaviour comes from.
This needs looking into, but is not high priority

**Comment by Yaksinikos** [comment]
Links 
Studienplan M.Sc. Informatik: Games Engineering — [ge-ma-sp.tum.sexy](https://ge-ma-sp.tum.sexy/)
Studienplan B.Sc. Informatik: Games Engineering — [ge-sp.tum.sexy](https://ge-sp.tum.sexy/)


Funktionieren auch nicht mehr ...

**Comment by CommanderStorm** [comment]
@Yaksinikos the redirect partially works now.
Sadly during the switch from in.tum.de -> cit.tum.de a lot of URLs broke as they did not care for backwards compatibility.
PRs appreciated.
