### ISSUE TITLE
Top Contributers not working after transition to TUM-Dev

### ISSUE THREAD

**Issue by joschahenningsen** [TUM-Dev/TUM.sexy#5]
Since @mammuth (btw. thank's for the lovely work in the past!) transfered this repository to TUM-Dev, the "hall of fame" in README.md (see 3b01c9080fb5a950839f9df7434c867faf6d1308) doesn't work anymore.
I suggest creating a new sourcerer.io account and updating the links.

Cheers!

**Comment by kordianbruck** [comment]
Good point, doing this now.
