### ISSUE TITLE
SSL certificate is broken on iOS & macOS 😕

### ISSUE THREAD

**Issue by markusdosch** [TUM-Dev/TUM.sexy#96]
See screenshot (iOS 15.0.1).

![image](https://user-images.githubusercontent.com/757612/137760234-a37844b9-0af1-49c3-b336-fe03ec585977.jpeg)

**Comment by kordianbruck** [comment]
You probably need to update your certificates so you get the new letsencrypt root cert: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
